name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json \
            | grep -oE '"version": "[0-9]+\.[0-9]+(\.[0-9]+)?"' \
            | head -n1 \
            | sed -E 's/.*"version": "([^"]+)".*/\1/')
          echo "go_version=$go_version" >> "$GITHUB_OUTPUT"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Build geoip
        id: build
        run: go run -v .
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          mkdir dist
          sha256sum geoip.db > dist/geoip.db.sha256sum
          sha256sum geoip-cn.db > dist/geoip-cn.db.sha256sum
          sha256sum geoip-lite.db > dist/geoip-lite.db.sha256sum
          cp geoip.db* dist/
          cp geoip-cn.db* dist/
          cp geoip-lite.db* dist/

      - name: Push artifacts to release branch
        if: steps.build.outputs.skip != 'true'
        run: |
          git config --local user.email "891708+soffchen@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          git checkout --orphan release-orphan
          git rm -rf .

          cp dist/* .
          git add geoip.db
          git add geoip-cn.db
          git add geoip-lite.db
          git add geoip.db.sha256sum
          git add geoip-cn.db.sha256sum
          git add geoip-lite.db.sha256sum

          git commit -am "Updated at $(date)"
          git branch -D release
          git branch -m release

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true

      - name: Create a release
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          name: ${{ steps.build.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            geoip.db
            geoip-cn.db
            geoip-lite.db
            geoip.db.sha256sum
            geoip-cn.db.sha256sum
            geoip-lite.db.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
